// import { RootState } from '@/stores/core/store';
// export const selectFiltersData = (state: RootState) => state.filters.data;
// export const selectFiltersStatus = (state: RootState) => state.filters.status;
// export const selectFiltersError = (state: RootState) => state.filters.error;
// export const selectSelectedFilters = (state: RootState) => state.filters.selectedFilters;
// export const selectFilterBy = (state: RootState) => state.filters.filterBy;
// export const selectFilterOps = (state: RootState) => state.filters.filterOps;
// export const selectCategory = (state: RootState) => state.filters.category;
// export const selectSortField = (state: RootState) => state.filters.sort.field;
// export const selectSortOrder = (state: RootState) => state.filters.sort.order;
